spring:
  cloud:
    gateway:
      routes:
      - id: xxooroute
        uri: http://localhost:8080
        predicates:
          - Cookie=name,jinchao
#          - Path=/api/gateway/**
#          - Query=num,.
#          - Method=get
#          - Host=mashibing.com

        filters:
        - StripPrefix=2
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
